version: "3"

services:
   resgisteruserapp-eurekaserver:
     image: souviksarkar9/registeruserapp-eurekaserver
     networks:
       - producer-consumer-repo-network
     ports:
       - 9001:9001
     deploy:
       replicas: 2
       update_config:
         delay: 10s 
       restart_policy:
         condition: on-failure
         delay: 5s
         max_attempts: 3
         
   resgisteruserapp-repository:
     image: souviksarkar9/registeruserapp-repository
     volumes: 
       - /usr/local/bin/registeruserapp:/usr/local/bin/registeruserapp
     networks:
       - producer-consumer-repo-network
     ports:     
       - 9002:9002
     deploy:
       replicas: 2
       update_config:
         delay: 10s 
       restart_policy:
         condition: on-failure
         delay: 5s
         max_attempts: 3              
     environment:
       server.port: 9002
       eureka.client.enabled: 'true'
       eureka.host: resgisteruserapp-eurekaserver
       eureka.instance.preferIpAddress: 'true'
     depends_on:
       - resgisteruserapp-eurekaserver
   
   resgisteruserapp-producer:
     image: souviksarkar9/registeruserapp-producer
     networks:
       - producer-consumer-repo-network
     ports:
       - 9003:9003
     deploy:
       replicas: 2      
       update_config:
         delay: 10s 
       restart_policy:
         condition: on-failure
         delay: 5s
         max_attempts: 3        
     environment:
       server.port: 9003
       eureka.client.enabled: 'true'
       eureka.host: resgisteruserapp-eurekaserver
       eureka.instance.preferIpAddress: 'true'       
     depends_on:
       - resgisteruserapp-eurekaserver
       - resgisteruserapp-repository       
                   
   resgisteruserapp-consumer:
     image: souviksarkar9/registeruserapp-consumer
     networks:
       - producer-consumer-repo-network  
     ports:
       - 9004:9004
     deploy:
       replicas: 2      
       update_config:
         delay: 10s 
       restart_policy:
         condition: on-failure
         delay: 5s
         max_attempts: 3        
     environment:
       server.port: 9004
       eureka.client.enabled: 'true'
       eureka.host: resgisteruserapp-eurekaserver
       eureka.instance.preferIpAddress: 'true'       
     depends_on:
       - resgisteruserapp-eurekaserver
       - resgisteruserapp-repository       
        
       
networks:
   producer-consumer-repo-network:          
       
       
       
       
       
       
              