 server:
  port: 8999
  
 spring:
  application:
    name: user-repository 
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

      
      
