 server:
  port: 9002
  
 spring:
  datasource:
    url: jdbc:h2:file:/usr/local/bin/registeruserapp/repo

  application:
    name: user-repository 
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

 eureka:
  instance:
    preferIpAddress: true
    instance-id:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.106:9001/eureka/


      
      
