 server:
  port: 9002
  
 spring:
  application:
    name: user-repository 
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

 eureka:
  instance:
    preferIpAddress: true
    instance-id:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.1:9001/eureka/



      
      
