server:
  port: 9001 
   
eureka:
  instance:
    prefer-ip-address: true
    ipAddress: 192.168.0.106
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ipAddress}:${server.port}/eureka/
