server:
  port: 9001 
   
eureka:
  instance:
    hostname: 172.17.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${server.instance.hostname}:${server.port}/eureka/
