 server:
  port: 8777
  
 spring:
  application:
    name: user-consumer 
  main:
    allow-bean-definition-overriding: true

 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

      
