 server:
  port: 9003
  
 spring:
  application:
    name: user-producer 
  main:
    allow-bean-definition-overriding: true

 eureka:
  instance:
    preferIpAddress: true
    instance-id:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.106:9001/eureka/

      
