 server:
  port: 8888
  
 spring:
  application:
    name: user-producer 
  main:
    allow-bean-definition-overriding: true

 eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:9000/eureka/

      
